name = "blog"
compatibility_date = "2024-09-19"

[assets]
directory = ".output/public"
not_found_handling = "single-page-application"
html_handling = "force-trailing-slash"

[[routes]]
pattern = "blog.naito.dev"
custom_domain = true
