name = "blog"
compatibility_date = "2024-09-19"
main = ".output/server/index.mjs"

[assets]
directory = ".output/public"
html_handling = "drop-trailing-slash"

[[routes]]
pattern = "blog.naito.dev"
custom_domain = true

[vars]
NUXT_STUDIO_AUTH_GITHUB_CLIENT_ID = "Ov23liPcajld1CHyJMQY"
